name: Build WireGuard for OpenWrt

# 手动触发workflow
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit Hash (e.g., r3071-73fdfdf6a)'
        required: true
        default: '522855254'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: 5b1838d04
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout OpenWrt repository
      uses: actions/checkout@main

    - name: Set up OpenWrt build environment
      run: |
        # 更新 feed 并安装依赖
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure build for WireGuard
      run: |
        # 选择编译 WireGuard 内核模块和工具
        make menuconfig
        make defconfig

    - name: Build WireGuard kernel module and tools
      run: |
        make package/kernel/linux/compile V=s
        make package/network/utils/wireguard-tools/compile V=s

    - name: Upload built artifacts
      uses: actions/upload-artifact@main
      with:
        name: wireguard-ipks
        path: bin/packages/mipsel_24kc/*
